// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectPlanner.Infrastructure.Persistence;

#nullable disable

namespace ProjectPlanner.Infrastructure.Migrations;

[DbContext(typeof(ProjectPlannerDbContext))]
partial class AddAttachmentDocumentStructure
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
